name: 🎨 디자인
description: UI/UX 디자인 작업을 위한 이슈를 생성합니다
title: "[DESIGN] 디자인 작업 제목"
labels: [
  "type:design"
]
assignees: []
body:
  - type: input
    id: issue-id
    attributes:
      label: Issue ID
      description: 버전-팀-번호 형식으로 입력하세요 (예: v1.0.0-DS-01)
      placeholder: "v1.0.0-DS-01"
    validations:
      required: true

  - type: textarea
    id: design-goal
    attributes:
      label: 디자인 목표 (Design Goal)
      description: 이 디자인 작업으로 달성하고자 하는 사용자 경험 목표
      placeholder: |
        사용자가 회원가입부터 로그인까지의 과정을 직관적이고 안전하게 경험할 수 있도록 인증 플로우 전체의 일관된 UI/UX를 설계한다.
    validations:
      required: true

  - type: textarea
    id: user-scenarios
    attributes:
      label: 사용자 시나리오 (User Scenarios)
      description: 디자인해야 할 주요 사용자 시나리오들
      placeholder: |
        - 신규 사용자가 처음 서비스를 발견하고 회원가입을 시도하는 상황
        - 이메일 인증을 완료하고 첫 로그인을 하는 상황
        - 비밀번호 정책을 만족하지 않아 에러 메시지를 받는 상황
        - 세션이 만료되어 재로그인이 필요한 상황
    validations:
      required: true

  - type: textarea
    id: design-requirements
    attributes:
      label: 디자인 요구사항 (Design Requirements)
      description: 구체적으로 디자인해야 할 화면이나 컴포넌트들
      placeholder: |
        - 회원가입 폼 (이메일, 비밀번호, 비밀번호 확인)
        - 비밀번호 정책 안내 및 실시간 검증 표시
        - 이메일 인증 안내 화면
        - 로그인 폼
        - 각종 에러 상태 메시지 디자인
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: 완료 조건 (Acceptance Criteria)
      description: 이 디자인 작업이 완료되었다고 판단할 수 있는 구체적인 조건들
      placeholder: |
        - [ ] 모든 인증 관련 화면의 와이어프레임이 완성됨
        - [ ] 인터랙션 플로우가 정의됨
        - [ ] 에러 상태별 시각적 피드백이 디자인됨
        - [ ] 개발 가능한 수준의 UI 컴포넌트가 완성됨
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: 의존성 (Dependencies)
      description: 이 디자인 작업을 위해 필요한 선행 작업이나 영향을 받는 후속 작업들
      placeholder: |
        선행 작업:
        - 사용자 리서치 또는 기존 디자인 시스템 검토

        후속 작업에 영향:
        - v1.0.0-FE-01 (UI 구현) - 이 디자인 스펙 기반으로 구현
    validations:
      required: false

  - type: textarea
    id: design-constraints
    attributes:
      label: 디자인 제약사항 (Design Constraints)
      description: 디자인 시 고려해야 할 기술적 또는 비즈니스적 제약사항
      placeholder: |
        - 기술 스택: Svelte5 + Tailwind CSS + shadcn-svelte
        - 반응형 디자인 필수 (모바일, 태블릿, 데스크톱)
        - 접근성 가이드라인 (WCAG 2.1) 준수
        - 브랜드 아이덴티티와 일관성 유지
    validations:
      required: false