spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false


  lifecycle:
    timeout-per-shutdown-phase: 30s
server:
  shutdown: graceful

decorator:
  datasource:
    enabled: false

logging:
  level:
    root: WARN
    app.aipacemaker: INFO
  pattern:
    console: "%d{ISO8601} %5p [%t] %c{1.} - %m%n"

management:
  endpoints:
    web:
      exposure:
        include: health,metrics
  endpoint:
    health:
      show-details: when-authorized
